### ISSUE TITLE
stand scripts

### ISSUE THREAD

**Issue by Nuclearpotato69** [Compwnter/Storage#1]
Could you update the destiny stand script to have a gui or something and add a tutorial on how to use the novapurge stand thing

**Comment by Compwnter** [comment]
I don't have the time to update Destiny Stand at the moment. I'm sick and I have a lot of exams this week.
I've also updated the Novapurge Stand. Check it out and see if it helps!
If you have anything else you'd like to ask me, feel free to! I'll be closing this issue with this comment.
Have a nice day!
