### ISSUE TITLE
nova purge stand

### ISSUE THREAD

**Issue by Nuclearpotato69** [Compwnter/Storage#3]
so its still a bit broken i saw a vid where the main acc gets a gui and stuff but it treats the main like a stand and could you make it a bit easier to config?

**Comment by Nuclearpotato69** [comment]
also the stand gui dont show up when i execute the stand gui from the one thats is under the stand script that says stand gui

**Comment by Nuclearpotato69** [comment]
k so i changed the speed and a few other things could you add a underground cmd that puts the stand under you so when you use save its faster

**Comment by Compwnter** [comment]
I'm not updating Nova Stand. Please stop asking me to update it.
